using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Linker
{
    partial class Linker
    {
        const string C_Code_Template = @"// this file was automatically generated by Linker.exe
#include <stdbool.h>
#include ""vm_globals.h""
#include ""loader.h""

#define CODE_SIZE {0}
static char emb_code[] = {{
{1}
}};

bool load_from_path(char *path)
{{
    gbl_code = emb_code;
    gbl_code_size = CODE_SIZE;
    return true;
}}
";

        public string Get_C_Code()
        {
            StringBuilder str = new StringBuilder();
            int l = code.Count;
            int i = 1;
            foreach (byte b in code)
            {
                str.Append(String.Format("0x{0}", b.ToString("X2")));
                if (i++ != l)
                {
                    str.Append(", ");
                }
            }
            return String.Format(C_Code_Template, l, str.ToString());
            //return C_Code_Template_part1 + str.ToString() + C_Code_Template_part2;
        }
    }
}
